### ISSUE TITLE
It seems that I am unable to use item payment in the latest Folia version plugin.

### ISSUE THREAD

**Issue by chameleon2020** [Niestrat99/AT-Rewritten#126]
Hello author, I saw your plugin on Modrinth, it's great because it has item payment feature and also supports Folia. But I downloaded the latest build version, and when I set the configuration file to use 8 Ender Pearls, then reload the server, there is no response.The following is my configuration file.

cost-amount: ENDER_PEARL:8

# Command-specific costs.
per-command-cost:
  # Cost for /tpa.
  tpa: ENDER_PEARL:8
  # Cost for /tpahere.
  tpahere: ENDER_PEARL:8
  # Cost for /tpr, or /rtp.
  tpr: ENDER_PEARL:8
  # Cost for /warp
  warp: ENDER_PEARL:8
  # Cost for /spawn
  spawn: ENDER_PEARL:8
  # Cost for /home
  home: ENDER_PEARL:8
  # Cost for /back
  back: ENDER_PEARL:8

**Comment by chameleon2020** [comment]
[17:13:31 WARN]: [AdvancedTeleport] Failed to parse payment WOOL:3:1 for command tpa! Error message: There is no economy provider for WOOL:3 registered.

**Comment by Thatsmusic99** [comment]
AT v6 does not use data IDs like in 1.8 servers anymore - it'll just be a full list that doesn't include the legacy IDs here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

Also ensure you're not OPed if you aren't getting charged.

**Comment by chameleon2020** [comment]
Thank you for your response. I'm sorry, but I still don't quite understand. If I want to set it to consume 8 Ender Pearls, what should I fill in after 'cost-amount:'?

**Comment by Thatsmusic99** [comment]
For ender pearls, it's `ENDER_PEARL:8` as you mentioned prior, which is correct - the wool one was just incorrect. If there are no warnings in the console when reloading the config or restarting the server, that generally means everything is set up correctly.

If you're not being charged, then you may be bypassing the cost if you have admin permissions or are OP.

Folia support is also still very experimental, especially since Folia itself isn't ready for production use - there are quite a few things that Folia has broken in AT that otherwise work normally on regular Paper servers.

**Comment by chameleon2020** [comment]
I tested it using an account without administrator privileges, and it indeed doesn't work when using item payment. However, when I changed it to using EXP payment, it works well. Using EXP payment is also a good choice. Supporting Folia is indeed a challenging task. Thank you for your creation.
