### ISSUE TITLE
Bug with capitalization in warp names for individual permissions

### ISSUE THREAD

**Issue by eodrambo** [Niestrat99/AT-Rewritten#20]
there's a bug with capitalization:
setting at.member.warp.Test - for a warp named "Test" does not work
setting at.member.warp.test - for a warp named "test" does work

**Comment by Niestrat99** [comment]
Usually permission nodes are always writtin in lowercase thats why warp names only work when the permission node is completely written in lowercase.

**Comment by eodrambo** [comment]
Probably just a documentation thing thing, or disallow capitalization in the warp name.

**Comment by Thatsmusic99** [comment]
Nah, it's not a documentation thing, it's been a reproduced bug and I'm looking into it now

**Comment by Thatsmusic99** [comment]
Turns out this is just a general weakness of permissions plugins. AT did make sure to check if the player had the permission to warp but it turns out that permissions are always stored in lowercase formats, whilst AT is case sensitive with its permissions. [This is no longer the case in this build.](https://cdn.discordapp.com/attachments/160644296385495040/750385878651895939/AdvancedTeleport-5.2.1.jar)
