### ISSUE TITLE
Plugin spams "Ping" and "Pong" in console

### ISSUE THREAD

**Issue by ThorinEk** [Niestrat99/AT-Rewritten#21]
Hello, when anyone on the server teleports somewhere, using seemingly any of the possible tp-commands, "ping" and "pong" is spammed in the chat:
https://paste.ubuntu.com/p/t7zNHhPxsc/

I am very satisfied with this plugin, it works very well and has all the features a teleport-plugin should!

**Comment by Thatsmusic99** [comment]
Hi there,

If you are using v5.2.2 of AdvancedTeleport, please update to the latest version of v5.2.3. You can confirm this using /version AdvancedTeleport.

I removed those messages in that version.

Thanks in advance!

**Comment by ThorinEk** [comment]
Thanks for the info! I seem to have missed the update yesterday...

**Comment by Thatsmusic99** [comment]
Not even yesterday, this update was released a day after v5.2.2 and is a month old now! 

No problem either way, but in response to this, I will try and make it clear within the plugin whether there's a new version or not (currently, it only says whether there is a new version or not when the server starts - I want to make it so that admins know an update is required upon login or using /atinfo).
