### ISSUE TITLE
Display/Formatting Options for Teleportation Costs

### ISSUE THREAD

**Issue by ForeverZer0** [Niestrat99/AT-Rewritten#51]
## Is your feature request related to a problem? Please describe.

Technically this two separate issues, though they are both related. 

First, I would like to request the ability to disable payment messages when the amount is 0. For example, there is a cost to use the commands such as `/rtp` and `/tpa`, but not for `/spawn`. Unfortunately, anytime a player uses the `/spawn` command, they are given the message:

>You have paid $0.0 and now have $549.69999999999!

I would like to avoid alerting someone that they have paid zero amount, as this is unnecessary and simply clogs the chat with unneeded messages, though I do very much wish to keep it enabled when there **is** a cost to the teleportation, as that  is useful.

This also brings me to the second issue, which is formatting. As you can see from the example above (a verbatim message), the amount is incorrectly formatted. I am using a format standard to the United States, which is the currency prefixed to the left, and always rounded to two decimal places, even when 0.

My configuration in EssentialsX looks like this:

```yaml
currency-format: "#,##0.00"
currency-symbol-format-locale: en-US
```

...though altering these values does not seem to have any effect after restarting the server. I am admittedly unsure if these values are even being used by this plugin, even indirectly.

## Describe the solution you'd like

* A config option to disable messages when they have zero cost.
* A config option to define the currency formatting, or at the least respect what is defined in other "standard" plugins such as Essentials.

## Describe alternatives you've considered

In my specific scenario, all of my costs are whole amounts, so I am able to hard-code a trailing `0` to them, which fixes the "paid" amount, though it has no effect on the "total" amount, where removing it would be the only solution I can see.

I personally cannot think of any solution for not showing zero-cost messages aside from disabling it altogether without being able to simply define it myself as an option.

## Additional context

* Same issue persisted on all latest 1.17 and 1.17.1 versions of both Spigot and Purpur that I have used over the past ~2 months
* AdvancedTeleport 5.5.3
* EssentialsX 2.19.0
* Vault 1.7.3-b131

**Comment by Thatsmusic99** [comment]
Java's floating point arithmetic often produces the most ridiculous results (then again... does any language do it better?), but considering I'm already working on fixing this properly in my other plugin (HeadsPlus), it should be easy to do.

As for the 0 cost problem, that's perfectly reasonable and can be considered a bug, but in the past I've often told people to work around it by setting the cost to two quotation marks '' since the pricing system in AT allows multiple payment methods, and it considers 0 as one of those. However, if it's an empty string - i.e. '' - it'll completely ignore it. Although, considering the number of people who have brought this up, chances are I'm the one doing it wrong and need to address that.

Thanks for the feedback!

**Comment by Thatsmusic99** [comment]
Oh yes, and values in EssX do not affect AT's functionality with messages, I only have the plugin hooked into EssX to allow people to easily import/export data between the plugins, but otherwise, AT ignores it altogether (but there are plenty of conflicts with the command systems at this time, which often require a server restart to address and something I may want to look into sometime...)

**Comment by ForeverZer0** [comment]
Using an empty string did indeed fix the issue with a zero balance being displayed. I apologize, I have no clue how I missed the comment in the config that instructed to do so, even after reading it multiple times while looking for a solution. 

Thank you for the quick reply, I look forward to any solution you can offer for the float rounding issue, and thank you for sharing such a high-quality plugin, it is very much appreciated.
