### ISSUE TITLE
Support for translations

### ISSUE THREAD

**Issue by Tajnymag** [Niestrat99/AT-Rewritten#9]
Could you please move out the hardcoded strings in CustomMessages.java to a separate messages_en.properties similarly to how Essentials handles it?

Users could then translate the messages to their language and submit the translations back to your repo.

How Essentials handles it:
https://github.com/EssentialsX/Essentials/tree/2.x/Essentials/src
https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/messages_en.properties
https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/I18n.java

**Comment by Thatsmusic99** [comment]
Please do keep in mind my word won't be final on this, but I am personally voting for a no on this, as I've already got a similar system in my plugin where people submit their own translations. It is an awfully tedious and extremely painful process to keep messages up to date, especially in multiple languages that you're not fluent in and can be seriously demotivating when trying to make a cool update for the plugin, then you realise you have to update all of the messages using Google Translate.

Essentials has its own way of handling things as well, we are two separate plugins. Whilst the I18n class does interest me and I may look further into it (i.e. learning from Essentials rather than taking the idea directly from it), I am personally against this idea. Nie may feel differently on the other hand.

**Comment by Niestrat99** [comment]
Thank you for your suggestion, however I'll as well vote for a no there because, as Thatsmusic99 has already mentioned, Essentials has it's own way of handling things and the way they handle it is beyond her's and my level.

Also personally having a custom-messages.yml is better than having translation files because it gives you far more possibilities of customizing the messages on your likings including colors, formats and obviously the messages themself.

Closing this issue.
